config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'welcome/index'
	resources :waterfalls do
		resources :comments, only: [:create, :destroy]
	end
	resources :posts

  root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
       
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :waterfall
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :waterfall
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/waterfall.rb
class Waterfall < ActiveRecord::Base
	has_many :comments
	has_many :pictures
	validates :title, presence: true,
                    length: { minimum: 5 }
  has_attached_file :avatar, :styles => { :medium => "500x500>", :thumb => "200x200>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/     
  validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/]            
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @waterfall = Waterfall.find(params[:waterfall_id])
    @comment = @waterfall.comments.create(comment_params)
    redirect_to waterfall_path(@waterfall)
  end

  def destroy
    @waterfall = Waterfall.find(params[:waterfall_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to waterfall_path(@waterfall)
	end

	 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@q = Post.ransack(params[:q])
    	@posts = @q.result(distinct: true).page(params[:page]).per(15).order('date DESC')
	end
	
	def show
		@post = Post.find(params[:id]) 	
	end

	def new
		@post = Post.new
  	end
	
  	def edit
		@post = Post.find(params[:id])  	
  	end
	
	def create
		@post = Post.new(post_params)
 
  		if @post.save
  			flash[:notice] = "Saved"
  			redirect_to @post
  		else
  			render 'new'
  		end
  	end

	def update
  		@post = Post.find(params[:id])
 
  		if @post.update(post_params)	
    		redirect_to @post
  		else
    		render 'edit'
  		end	
	end
	
	def destroy
	  	@post = Post.find(params[:id])
  		@post.destroy
  		redirect_to posts_path
	end


  	private
  		def post_params
    		params.require(:post).permit(:title, :text, :date)
  		end

end

app/controllers/waterfalls_controller.rb
class WaterfallsController < ApplicationController
  	
  	def index
  		@q = Waterfall.ransack(params[:q])
    	@waterfalls = @q.result(distinct: true).page(params[:page]).per(15).order('title ASC')
  	end  	
  	
  	def show
   	@waterfall = Waterfall.find(params[:id])
  	end
	
	def new
		@waterfall = Waterfall.new
	end
	
	def edit
  		@waterfall = Waterfall.find(params[:id])
	end
		
	def create
		@waterfall = Waterfall.new(waterfall_params)
 
  		if @waterfall.save
  			flash[:notice] = "Saved"
  			redirect_to @waterfall
  		else
  			render 'new'
  		end
  	end
	
	def update
  		@waterfall = Waterfall.find(params[:id])
 
  		if @waterfall.update(waterfall_params)	
    		redirect_to @waterfall
  		else
    		render 'edit'
  		end
	end  	

  	def destroy
  		@waterfall = Waterfall.find(params[:id])
  		@waterfall.destroy
 
  		redirect_to waterfalls_path
	end
  	private
  		def waterfall_params
    		params.require(:waterfall).permit(:title, :text, :height, :width, :drops, :tallestDrop, :form, :watershed, :stream, :location, :state, :visit, :avatar, :imageName, :index)
  		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def markdown (text)
		options = [:hard_wrap, :autolink, :no_intraemphasis, :fenced_code, :gh_blockcode]
		Markdown.new(text, *options).to_html.html_safe	
	end
end

app/helpers/waterfalls_helper.rb
module WaterfallsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-primary" %><br>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-primary" %><br>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "btn btn-primary" %><br>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "btn btn-primary" %><br>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "btn btn-primary" %><br>
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: "btn btn-primary" %><br>
  <% end -%>
<% end -%>

app/views/comments/_comment.html.erb
<p>
  <strong>Name:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p><br>
 
<p>
  <% if admin_signed_in? %>
  		<%= link_to 'Delete', [comment.waterfall, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
	<% end %>
</p><br>

app/views/comments/_form.html.erb
		<%= form_for([@waterfall, @waterfall.comments.build]) do |f| %>
  		<p>
    		<%= f.label :commenter, "Name" %><br>
    		<%= f.text_field :commenter %>
  		</p>
  		<p>
    		<%= f.label :body, "Comment" %><br>
    		<%= f.text_area :body, class: "form-control", rows: 10 %>
  		</p>
  		<p>
    		<%= f.submit "Submit", class: "btn btn-primary" %>
  		</p><br>
		<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Waterfalls</title>
	<!-- Latest compiled and minified CSS -->
	<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"%>
	<!-- Optional theme -->
	<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"%>
  <%= stylesheet_link_tag "normalize" %>
  <%= stylesheet_link_tag "main" %>  
  <%= stylesheet_link_tag "waterfalls" %>  
  <%= stylesheet_link_tag "admin" %>  
  <%= stylesheet_link_tag "posts" %>  
  <%= stylesheet_link_tag "query" %>    
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Ubuntu:400,700" %>  
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" %> 
  <%= csrf_meta_tags %>
</head>
<body data-vide-bg="../videos/background.mp4" data-vide-options="loop: true, muted: true">
<nav class="navbar navbar-default navbar-static-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<i class="fa fa-bars"></i>
          </button>
          	<h2 id="main-title">Adam's Wonderful World of Waterfalls</h2>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to('Home', root_path) %></li>
            <li><%= link_to 'Waterfalls', controller: '/waterfalls' %></li>
            <li><%= link_to 'Blog', controller: '/posts' %></li>
            <% if admin_signed_in? %>
					<li><%= link_to('Log Out', destroy_admin_session_path, :method => :get) %></li>
				<% end %>            
          </ul>
        </div>
      </div>
    </nav>
    
<%= yield %>
    <footer class="footer">
      <div class="container-fluid">
        <h4>© 2016 Adam Bodie, Inc.</h4>
      </div>
    </footer>
<!-- Latest compiled and minified JavaScript -->
<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js" %>
<%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" %>
<%= javascript_include_tag "jquery.sticky"%>
<%= javascript_include_tag "jquery.vide.min" %>  
<%= javascript_include_tag "sticky" %>
<%= javascript_include_tag "animation" %>
<%= javascript_include_tag "overlay" %>  


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, url: @posts_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </p> 
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, size: "80x15" , autocomplete: 'off'  %>
  </p>
 
  <p>
    <%= f.submit "Upload", class: "btn btn-primary" %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<div class="post-form"> 
<%= render 'form' %>
</div>

app/views/posts/index.html.erb
	<% if admin_signed_in? %>
		<%= link_to 'New', new_post_path(), class: "btn btn-primary" %>
	<% end %>

  			<% @posts.each do |post| %>
  			<div class="row posts">
  				<div class="col-md-3"></div>
      		<div class="col-md-6">
      		   <h4 class="post-title"><%= post.title %></h4>
      		   <h6 class="auth">by Adam Bodie</h6>
  					<h6 class="auth"><%= post.date.strftime("%B %d, %Y") %></h6>	
      			<%= link_to 'Click to Read', post_path(post), class: "btn btn-primary read"%>
      		</div>
      		<% if admin_signed_in? %>
      			<div class="col-md-3">	
	   	   		<%= link_to 'Edit', edit_post_path(post), class: "btn btn-primary" %>
	   	   		<%= link_to 'Delete', post_path(post),
   		   	        method: :delete,
      		   	     data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
      		   </div>
      		   <% else %>
      		   	<div class="col-md-3"></div>
				<% end %> 
			</div>
			<% end %>   	

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="row post">
  <h3 class="post-title"><strong><%= @post.title %></strong><h3>
	<div class="col-md-3"></div>
	<div class="col-md-6">
  		<h5 class="author">by Adam Bodie</h5>
  		<h5 class="author"><%= @post.date.strftime("%B %d, %Y") %></h5>	
		<p><%= markdown(@post.text)%></p>
	</div>
	<div class="col-md-3"></div>
</div>
 
<%= link_to 'Back', posts_path, class: "btn btn-primary" %>

app/views/waterfalls/_form.html.erb
<div class="form">
<%= form_for @waterfall, url: @waterfalls_path, :html => { :multipart => true } do |f| %>
<div class="row">
  <% if @waterfall.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@waterfall.errors.count, "error") %> prohibited
        this waterfall from being saved:
      </h2>
      <ul>
        <% @waterfall.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, autocomplete: 'off' %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, size: "70x5" , autocomplete: 'off' %>
  </p>
  </div>
  	<div class="row">
 		<div class="col-md-3">
  			<p>
    			<%= f.label :height %><br>
    			<%= f.text_field :height, autocomplete: 'off' %>
  			</p> 
		</div>
	 	<div class="col-md-3">
  			<p>
   		 	<%= f.label :width %><br>
    			<%= f.text_field :width, autocomplete: 'off' %>
  			</p>
  		</div>
   	<div class="col-md-3">
    		<p>
    			<%= f.label :drops %><br>
    			<%= f.text_field :drops, autocomplete: 'off' %>
  			</p>
  		</div>
  	</div>
  	<div class="row">
 		<div class="col-md-3">  	  		
    		<p>
    			<%= f.label :tallestDrop %><br>
    			<%= f.text_field :tallestDrop , autocomplete: 'off'%>
  			</p>
    	</div>
 		<div class="col-md-3">      	
    		<p>
    			<%= f.label :form %><br>
    			<%= f.text_field :form , autocomplete: 'off'%>
  			</p>
		</div>
	</div>
  	<div class="row">
 		<div class="col-md-3">	  
  			<p>
    			<%= f.label :watershed %><br>
    			<%= f.text_field :watershed , autocomplete: 'off'%>
  			</p>
  		</div>
	 	<div class="col-md-3">	  
			<p>
    			<%= f.label :stream %><br>
    			<%= f.text_field :stream, autocomplete: 'off' %>
  			</p>
  		</div>
 		<div class="col-md-3">
 			<p>
    			<%= f.label :location %><br>
    			<%= f.text_field :location, autocomplete: 'off' %>
  			</p>
		</div>
	</div>
  	<div class="row">
 		<div class="col-md-3">	    
    		<p>
    			<%= f.label :state %><br>
    			<%= f.text_field :state, autocomplete: 'off' %>
  			</p> 
		</div>
	 <div class="col-md-3">		
	 	<p>
    		<%= f.label :visit %><br>
    		<%= f.text_field :visit, autocomplete: 'off' %>
  		</p>
	</div>
	<div class="col-md-3">		   
   	<p>
    		<%= f.label :imageName %><br>
    		<%= f.text_field :imageName, autocomplete: 'off' %>
  		</p>
  	</div>
	<div class="col-md-3">		   
   	<p>
    		<%= f.label :index %><br>
    		<%= f.text_field :index, autocomplete: 'off' %>
  		</p>
  	</div>  	
  </div>	 
 <p>
		<%= f.file_field :avatar%>  
 </p>
  	<p>
   	<%= f.submit "Upload", class: "btn btn-primary" %>
  		<%= link_to 'Back', waterfalls_path, class: "waterfall-title btn btn-primary"  %>
	</p>  	
<% end %>
</div>

app/views/waterfalls/edit.html.erb
<h1>Editing waterfall</h1>
 
<%= render 'form' %>

app/views/waterfalls/index.html.erb
<div class="container-fluid">
	<div class="page">
	<% if admin_signed_in? %>
		<%= link_to 'New', new_waterfall_path(), class: "btn btn-primary" %>
	<% end %>
		<div class="row">
				<div class="pages">
					<%= paginate @waterfalls %>
				</div>
		</div>	
	<div class="row waterfall key">
			<div class="col-sm-4">
   				<h4 class="waterfall-title"><%= sort_link(@q, :title) %></h4>
   		</div>
			<div class="col-sm-2 other">
					<h4><%= sort_link(@q, :location) %></h4>
			</div>	
			<div class="col-sm-2 other">
					<h4><%= sort_link(@q, :state) %></h4>
			</div>		
			<div class="col-sm-1 other">
					<h4><%= sort_link(@q, :height, default_order: :desc) %></h4>		
			</div>
			<div class="col-sm-1 other">
					<h4><%= sort_link(@q, :width, default_order: :desc) %></h4>		
			</div>
			<div class="col-sm-1 other">
					<h4><%= sort_link(@q, :form) %></h4>
			</div>			
	</div>

  			<% @waterfalls.each do |waterfall| %>
  			<div class="row waterfall">
				<div class="col-sm-2">
      			<h4 class="waterfall-title"><%= link_to waterfall.title, waterfall_path(waterfall)%></h4>
      		</div>
      		<div class="col-sm-2">		
      			<h4><%= image_tag waterfall.avatar.url(:thumb), class: "img-responsive small-picture"%></h4>
      		</div>
    			<div class="col-sm-2 other">		
      			<h5><%= waterfall.location%></h5>
      		</div>
      		<div class="col-sm-2 other">		
      			<h5><%= waterfall.state%></h5>
      		</div>
      		<div class="col-sm-1 other">		
      			<h5><%= waterfall.height%> feet</h5>
      		</div>
      		<div class="col-sm-1 other">		
      			<h5><%= waterfall.width%> feet</h5>
      		</div>
      		<div class="col-sm-1 other">		
      			<h5><%= waterfall.form%></h5>
      		</div>      		
      		<% if admin_signed_in? %>
      			<div class="col-sm-1 other">	
	   	   		<%= link_to 'Edit', edit_waterfall_path(waterfall), class: "btn btn-primary" %>
	   	   		<%= link_to 'Delete', waterfall_path(waterfall),
   		   	        method: :delete,
      		   	     data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
      		   </div>
      		   <% else %>
      		   	<div class="col-sm-3 other"></div>
				<% end %> 
			</div>   	
  			<% end %>

		<div class="row">
				<div class="pages">
					<%= paginate @waterfalls %>
				</div>
		</div>	

	</div> 
</div>

app/views/waterfalls/new.html.erb
<h1>Waterfall</h1>
<div class="page">
<%= render 'form' %>
</div>

app/views/waterfalls/show.html.erb
<h1><strong><%= @waterfall.title %></strong></h1>

<div class="container">
	<div class="page">
 		<div class="row">
 			<div class="col-sm-6">
 					<p><strong>Summary:</strong></p>
					<p><%= @waterfall.text %></p>
					<p><strong>Height:</strong> <%= @waterfall.height %> feet</p>
					<p><strong>Average width:</strong> <%= @waterfall.width %> feet</p>
					<p><strong>Drops:</strong> <%= @waterfall.drops %></p>
					<p><strong>Tallest drop:</strong> <%= @waterfall.tallestDrop %> feet</p>		
					<p><strong>Waterfall form:</strong> <%= @waterfall.form %></p>
					<p><strong>Watershed:</strong> <%= @waterfall.watershed %></p>
					<p><strong>Stream:</strong> <%= @waterfall.stream %></p>
					<p><strong>Location:</strong> <%= @waterfall.location %></p>
					<p><strong>State:</strong> <%= @waterfall.state %></p>
					<% if @waterfall.visit == true %>					
						<p><strong>Visited:</strong> Yes</p>
					<% else %>
						<p><strong>Visited:</strong> No</p>
					<% end %>
			</div>
 			<div class="col-sm-6 carousel">
 			<a href="../images/<%=@waterfall.imageName%>.jpg" >			
				<%= image_tag @waterfall.avatar.url(:medium), class:"img-responsive big-picture" %>
			</a>			
			</div>			
		</div>
		<div class="row carousel">
		<% if @waterfall.index != 0 %>
			<h3>Additional Pictures</h3>
		<% end %>
		<% for i in (2..(@waterfall.index + 1)) do %>
				<div class="col-sm-3 small-picture">
					<a href="../images/<%=@waterfall.imageName%><%= i %>.jpg" class="img-responsive">
					<img src="../images/<%=@waterfall.imageName%><%= i %>.jpg" class="img-responsive">
					</a>
				</div>
		<% end %>	
		</div>		
		<div class ="row comments">
 			<div class="col-sm-6">
				<h3>Comments</h3>
				<%= render @waterfall.comments %>
			</div> 		
 		</div>
 		<div class ="row">
 			<div class="col-sm-6">
				<h3>Add a comment:</h3>
				<%= render 'comments/form' %>
			</div>
		</div>
		<% if admin_signed_in? %>
			<%= link_to 'Edit', edit_waterfall_path(@waterfall), class: "waterfall-title btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/welcome/index.html.erb
<div class="container" id="front-page">
	<div class="row">
		<%= image_tag "mobile.jpg", class: "img-responsive mobile"%>
		<div class="video">
			<div id="one" class="block"></div>
			<div id="two" class="block"></div>
			<div id="three" class="block"></div>
			<div id="four" class="block"></div>
			<div id="five"class="block" ></div>
			<div id="six" class="block"></div>
		</div>
	</div>
</div>
	